export const wards = [
  // Adamaawa State
  {
    state: "ADAMAWA",
    lga: "DEMSA",
    wards: [
      "BILLE",
      "BORRONG",
      "DEMSA",
      "DILLI",
      "DONG",
      "DWAM",
      "GWAMBA",
      "KPASHAM",
      "MBULA KULI",
      "NASSARAWO DEMSA",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "FUFORE",
    wards: [
      "BETI",
      "FARANG",
      "FUFORE",
      "GURIN",
      "KARLAHI",
      "MAYO INE",
      "PARIYA",
      "RIBADU",
      "UKI TUKI",
      "WURO BOKKI",
      "YADIM",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "GANYE",
    wards: [
      "BAKARI GUSO",
      "GAMU",
      "GANYE I",
      "GANYE II",
      "GURUM",
      "JAGGU",
      "SANGASUMI",
      "SUGU",
      "TIMDORE",
      "YEBBI",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "GIREI",
    wards: [
      "DAKRI",
      "DAMARE",
      "GERENG",
      "GIREI I",
      "GIREI II",
      "JERA BAKARI",
      "JERA BONYO",
      "MODIRE/ VINIKILANG",
      "TAMBO",
      "WURO DOLE",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "GOMBI",
    wards: [
      "BOGA/ DINGAI",
      "DUWA",
      "GA'ANDA",
      "GABUN",
      "GARKIDA",
      "GOMBI NORTH",
      "GOMBI SOUTH",
      "GUYAKU",
      "TAWA",
      "YANG",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "GUYUK",
    wards: [
      "BANJIRAM",
      "BOBINI",
      "BODENO",
      "CHIKILA",
      "DUKUL",
      "DUMNA",
      "GUYUK",
      "KOLA",
      "LOKORO",
      "PUROKAYO",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "HONG",
    wards: [
      "BANGSHIKA",
      "DAKSIRI",
      "GARAHA",
      "GAYA",
      "HILDI",
      "HONG",
      "HUSHERE ZUM",
      "KWARHI",
      "MAYO LOPE",
      "SHANGUI",
      "THILBANG",
      "UBA",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "JADA",
    wards: [
      "DANABA",
      "JADA I",
      "JADA II",
      "KOMA I",
      "KOMA II",
      "LEKO",
      "MAPEO",
      "MAYOKALAYE",
      "MBULO",
      "NYIBANGO",
      "YELLI",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "LAMURDE",
    wards: [
      "DUBWANGUN",
      "GYAWANA",
      "LAFIYA",
      "LAMURDE",
      "MGBEBONGUN",
      "NGBAKOWO",
      "OPALO",
      "RIGANGE",
      "SUWA",
      "WADUKU",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "MADAGALI",
    wards: [
      "BABEL",
      "DUHU/ SHUWA",
      "GULAK",
      "HYAMBULA",
      "K/WURO NGAYANDI",
      "MADAGALI",
      "PALLAM",
      "SHELMI / SUKUR/ VAPURA",
      "WAGGA",
      "WULA",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "MAYO - BELWA",
    wards: [
      "BAJAMA",
      "BINYERI",
      "GANGFADA",
      "GENGLE",
      "GOROBI",
      "MAYO FARANG",
      "MAYO-BELWA",
      "NASSARAWO JERENG",
      "NDIKONG",
      "RIBADU",
      "TOLA",
      "YOFFO",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "MICHIKA",
    wards: [
      "BAZZA MARGI",
      "FUTUDOU / FUTULES",
      "GARTA / GHUNCHI",
      "JIGALAMBU",
      "MADZI",
      "MICHIKA I",
      "MICHIKA II",
      "MINKISI/ WURO NGIKI",
      "MODA / DLAKA / GHENJUWA",
      "MUNKAVICITA",
      "SINA / KAMALE / KWANDE",
      "SUKUMU / TILLIJO",
      "THUKUDOU / SUFUKU / ZAH",
      "TUMBARA / NGABILI",
      "VI / BOKA",
      "WAMBLIMI / TILLI",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "MUBI NORTH",
    wards: [
      "BAHULI",
      "BETSO",
      "DIGIL",
      "KOLERE",
      "LOKUWA",
      "MAYO BANI",
      "MIJILU",
      "MUCHALLA",
      "SABON LAYI",
      "VIMTIM",
      "YELWA",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "MUBI SOUTH",
    wards: [
      "DIRBISHI/GANDIRA",
      "DUVU/ CHABA/ GIRBURUM",
      "GELLA",
      "GUDE",
      "KWAJA",
      "LAMORDE",
      "MUGULBU/ YADAFA",
      "MUJARA",
      "NASSARAWO",
      "NDUKU",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "NUMAN",
    wards: [
      "BARE",
      "BOLKI",
      "GAMADIO",
      "IMBURU",
      "KODOMTI",
      "NUMAN I",
      "NUMAN II",
      "NUMAN III",
      "SABON PEGI",
      "VULPI",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "SHELLENG",
    wards: [
      "BAKTA",
      "BODWAI",
      "GUNDO",
      "GWAPOPOLOK",
      "JUMBUL",
      "KETEMBERE",
      "KIRI",
      "LIBBO",
      "SHELLENG",
      "TALLUM",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "SONG",
    wards: [
      "DIRMA",
      "DUMNE",
      "GUDU MBOI",
      "KILANGE FUNA",
      "KILANGE HIRNA",
      "SIGIRE",
      "SONG GARI",
      "SONG WAJE",
      "SUKTU",
      "WALTANDI",
      "ZUMO",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "TOUNGO",
    wards: [
      "DAWO I",
      "DAWO II",
      "GUMTI",
      "KIRI I",
      "KIRI II",
      "KONGIN BABA I",
      "KONGIN BABA II",
      "TOUNGO I",
      "TOUNGO II",
      "TOUNGO III",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "YOLA NORTH",
    wards: [
      "AJIYA",
      "ALKALAWA",
      "DOUBELI",
      "GWADABAWA",
      "JAMBUTU",
      "KARENA",
      "LIMAWA",
      "LUGGERE",
      "NASSARAWO",
      "RUMDE",
      "YELWA",
    ],
  },
  {
    state: "ADAMAWA",
    lga: "YOLA SOUTH",
    wards: [
      "ADARAWO",
      "BAKO",
      "BOLE YOLDE PATE",
      "MAKAMA 'A'",
      "MAKAMA 'B'",
      "MBAMBA",
      "MBAMOI",
      "NAMTARI",
      "NGURORE",
      "TOUNGO",
      "YOLDE KOHI",
    ],
  },
  // Taraba State
  {
    state: "TARABA",
    lga: "ARDO - KOLA",
    wards: [
      "ALIM GORA",
      "ARDO KOLA",
      "IWARE",
      "JAURO YINU",
      "LAMIDO BORNO",
      "MAYO RANEWO",
      "SARKIN DUTSE",
      "SUNKANI",
      "TAU",
      "ZONGON KOMBI",
    ],
  },
  {
    state: "TARABA",
    lga: "BALI",
    wards: [
      "BADAKOSHI",
      "BALI A",
      "BALI B",
      "GANG DOLE",
      "GANG MATA",
      "GANGLARI",
      "GANGTIBA",
      "KAIGAMA",
      "MAIHULA",
      "SUNTAI",
      "TAKALAFIYA",
    ],
  },
  {
    state: "TARABA",
    lga: "DONGA",
    wards: [
      "AKATE",
      "ASIBITI",
      "BIKADARKO",
      "FADA",
      "GAYAMA",
      "GINDIN DUTSE",
      "GYATTA AURE",
      "MARARRABA",
      "NYITA",
      "SUNTAI",
    ],
  },
  {
    state: "TARABA",
    lga: "GASHAKA",
    wards: [
      "GALUMJINA",
      "GANGUMI",
      "GARBABI",
      "GASHAKA",
      "GAYAM",
      "JAMTARI",
      "MAI-IDANU",
      "MAYO SELBE",
      "SERTI 'A'",
      "SERTI 'B'",
    ],
  },
  {
    state: "TARABA",
    lga: "GASSOL",
    wards: [
      "GASSOL",
      "GUNDUMA",
      "MUTUM BIYU I",
      "MUTUM BIYU II",
      "NAM NAI",
      "SABON GIDA",
      "SARKIN SHIRA",
      "SENDIRDE",
      "TUTARE",
      "WUROJAM",
      "WURYO",
      "YARIMA",
    ],
  },
  {
    state: "TARABA",
    lga: "IBI",
    wards: [
      "DAMPAR I",
      "DAMPAR II",
      "DAMPAR III",
      "IBI NWONYO I",
      "IBI NWONYO II",
      "IBI RIMI UKU I",
      "IBI RIMI UKU II",
      "SARKIN KUDU I",
      "SARKIN KUDU II",
      "SARKIN KUDU III",
    ],
  },
  {
    state: "TARABA",
    lga: "JALINGO",
    wards: [
      "ABBARE YELWA",
      "BARADE",
      "KACHALLA SEMBE",
      "KONA",
      "MAJIDADI",
      "MAYO GOI",
      "SARKIN DAWAKI",
      "SINTALI",
      "TURAKI A",
      "TURAKI B",
    ],
  },
  {
    state: "TARABA",
    lga: "KARIM-LAMIDO",
    wards: [
      "AMAR",
      "ANDAMIN",
      "BACHAMA",
      "BIKWIN",
      "DAROFAI",
      "DIDANGO",
      "JEN ARDIDO",
      "JEN KAIGAMA",
      "KARIM A",
      "KARIM B",
      "KWANCHI",
    ],
  },
  {
    state: "TARABA",
    lga: "KURMI",
    wards: [
      "ABONG",
      "AKWENTO/BOKO",
      "ASHUKU/ENEME",
      "BAISSA",
      "BENTE/GALEA",
      "BISSAULA",
      "DIDAN",
      "NDAFORO/GEANDA",
      "NJUWANDE",
      "NYIDO/TOSSO",
    ],
  },
  {
    state: "TARABA",
    lga: "LAU",
    wards: [
      "ABBARE I",
      "ABBERE II",
      "DONADDA",
      "GARIN DOGO",
      "GARIN MAGAJI",
      "JIMLARI",
      "KUNINI",
      "LAU I",
      "LAU II",
      "MAYO LOPE",
    ],
  },
  {
    state: "TARABA",
    lga: "SARDAUNA",
    wards: [
      "GEMBU A",
      "GEMBU B",
      "KABRI",
      "KAKARA",
      "MAGU",
      "MAYO-NDAGA",
      "MBAMNGA",
      "NDUM-YAJI",
      "NGUROJE",
      "TITONG",
      "WARWAR",
    ],
  },
  {
    state: "TARABA",
    lga: "TAKUM",
    wards: [
      "BETE",
      "BIKASHIBILA",
      "CHANCHANJI",
      "DUTSE",
      "FETE",
      "GAHWETON",
      "MANYA",
      "ROGO",
      "SHIBONG",
      "TIKARI",
      "YUKUBEN",
    ],
  },
  {
    state: "TARABA",
    lga: "USSA",
    wards: [
      "FIKYU",
      "KPAMBO",
      "KPAMBO PURI",
      "KWESATI",
      "LISSAM I",
      "LISSAM II",
      "LUMBU",
      "RUFU",
    ],
  },
  {
    state: "TARABA",
    lga: "WUKARI",
    wards: [
      "AKWANA",
      "AVYI",
      "BANTAJE",
      "CHONKU",
      "HOSPITAL",
      "JIBU",
      "KENTE",
      "PUJE",
      "RAFIN KADA",
      "TSOKUNDI",
    ],
  },
  {
    state: "TARABA",
    lga: "YORRO",
    wards: [
      "BIKASSA I",
      "BIKASSA II",
      "NYAJA I",
      "NYAJA II",
      "PANTISAWA I",
      "PANTISAWA II",
      "PUPULE I",
      "PUPULE II",
      "PUPULE III",
      "SUMBU I",
      "SUMBU II",
    ],
  },
  {
    state: "TARABA",
    lga: "ZING",
    wards: [
      "BITAKO",
      "BUBONG",
      "DINDING",
      "LAMMA",
      "MONKIN A",
      "MONKIN B",
      "YAKOKO",
      "ZING AI",
      "ZING AII",
      "ZING B",
    ],
  },
  {
    state: "BAUCHI",
    lga: "ALKALERI",
    wards: [
      "ALKALERI",
      "BIRIN/ GIGARA/ YANKARI",
      "DAN KUNGIBAR",
      "FUTUK",
      "GAR",
      "GWANA / MANSUR",
      "GWARAM",
      "MAIMADI",
      "PALI",
      "YALO",
      "YULI/ LIM",
    ],
  },
  {
    state: "BAUCHI",
    lga: "BAUCHI",
    wards: [
      "BIRSHI/MIRI",
      "DANDANGO/YAMRAT",
      "DAN'IYA HARDO",
      "DAWAKI",
      "GALAMBI/GWASKWARAM",
      "KANGYARE/TURWUN",
      "KUNDUM/DURUM",
      "MAJIDADI 'A'",
      "MAJIDADI 'B'",
      "MAKAMA/SARKI BAKI",
      "MUN/MUNSAL",
      "ZUNGUR/LIMAN KATAGUM",
    ],
  },
  {
    state: "BAUCHI",
    lga: "BOGORO",
    wards: [
      "B O I A",
      "B O I B",
      "B O I C",
      "BOGORO A",
      "BOGORO B",
      "BOGORO C",
      "BOGORO D",
      "LUSA A",
      "LUSA B",
      "LUSA C",
    ],
  },
  {
    state: "BAUCHI",
    lga: "DAMBAM",
    wards: [
      "DAGAUDA",
      "DAMBAM",
      "GARGAWA",
      "GARUZA",
      "GURBANA",
      "JALAM CENTRAL",
      "JALAM EAST",
      "YAME",
      "YANDA",
      "ZAURA",
    ],
  },
  {
    state: "BAUCHI",
    lga: "DARAZO",
    wards: [
      "DARAZO",
      "GABARIN",
      "GABCIYARI",
      "KONKIYAL",
      "LAGO",
      "LANZAI",
      "PAPA",
      "SADE",
      "TAUYA",
      "WAHU",
      "YAUTARE",
    ],
  },
  {
    state: "BAUCHI",
    lga: "DASS",
    wards: [
      "BAGEL/BAJAR",
      "BARAZA",
      "BUNDOT",
      "BUNUNU CENTRAL",
      "BUNUNU SOUTH",
      "DOTT",
      "DURR",
      "POLCHI",
      "WANDI",
      "ZUMBUL/LUKSHI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "GAMAWA",
    wards: [
      "ALAGARNO/JADORI",
      "GADIYA",
      "GAMAWA",
      "GOLOLO",
      "KAFIN ROMI",
      "KUBDIYA",
      "RAGA",
      "TARMASUWA",
      "TUMBI",
      "UDUBO",
      "ZINDI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "GANJUWA",
    wards: [
      "Ganjuwa",
      "Gungura",
      "KAFIN MADAKI",
      "KARIYA",
      "Kubi East",
      "Kubi West",
      "MIYA EAST",
      "MIYA WEST",
      "NASARAWA SOUTH",
      "NASARAWA NORTH",
      "YALI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "GIADE",
    wards: [
      "CHINKANI",
      "DOGUWA SOUTH",
      "DOGUWA CENTRAL",
      "GIADE",
      "ISAWA",
      "SABON SARA",
      "UZUM A",
      "UZUM B",
      "ZABI",
      "ZIRRAMI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "ITAS/GADAU",
    wards: [
      "ABDALLAWA/MAGARYA",
      "BAMBAL",
      "BILKICHERI",
      "BUZAWA",
      "GADAU",
      "GWARAI",
      "ITAS",
      "KASHURI",
      "MASHEMA",
      "ZUBUKI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "JAMA'ARE",
    wards: [
      "DOGON JEJI A",
      "DOGON JEJI B",
      "DOGON JEJI C",
      "GALDIMARI",
      "HANAFARI",
      "JAMA'ARE A",
      "JAMA'ARE B",
      "JAMA'ARE C",
      "JAMA'ARE D",
      "JURARA",
    ],
  },
  {
    state: "BAUCHI",
    lga: "KATAGUM",
    wards: [
      "BULKACHUWA/DAGARO",
      "BUSKURI",
      "CHINADE",
      "GAMBAKI/BIDIR",
      "MADACHI/GANGAI",
      "MADANGALA",
      "MADARA",
      "NASARAWA BAKIN KASUWA",
      "RAGWAM/MAGONSHI",
      "TSAKUWA KOFAR GABAS/ KOFAR KUKA",
      "YAYU",
    ],
  },
  {
    state: "BAUCHI",
    lga: "KIRFI",
    wards: [
      "BADARA",
      "BARA",
      "BENI A",
      "BENI B",
      "DEWU CENTRAL",
      "DEWU EAST",
      "KIRFI",
      "SHANGO",
      "TUBULE",
      "WANKA",
    ],
  },
  {
    state: "BAUCHI",
    lga: "MISAU",
    wards: [
      "AJILIN/GUGULIN",
      "BETI",
      "GWARAM",
      "HARDAWA",
      "JARKASA",
      "KUKADI/GUNDARI",
      "SARMA/AKUYAM",
      "SIRKO",
      "TOFU",
      "ZADAWA",
    ],
  },
  {
    state: "BAUCHI",
    lga: "NINGI",
    wards: [
      "BALMA",
      "BASHE",
      "BURRA / KYATA",
      "DINGIS",
      "JANGU",
      "KUDU / YAMMA",
      "KURMI",
      "NASARU",
      "NINGI",
      "SAMA",
      "TIFFI / GUDA",
    ],
  },
  {
    state: "BAUCHI",
    lga: "SHIRA",
    wards: [
      "ANDUBUN",
      "BELI/GAGIDABA",
      "BUKUL/BANGIRE",
      "DISINA",
      "FAGGO",
      "KILBORI",
      "SAMBUWAL",
      "SHIRA",
      "TSAFI",
      "TUMFAFI",
      "ZUBO",
    ],
  },
  {
    state: "BAUCHI",
    lga: "TAFAWA BALEWA",
    wards: [
      "BALL",
      "BULA",
      "BUNUNU",
      "DAJIN",
      "DULL",
      "KARDAM A",
      "KARDAM B",
      "LERE SOUTH",
      "LERE NORTH",
      "TAPSHIN",
      "WAI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "TORO",
    wards: [
      "JAMA'A / ZARANDA",
      "LAME",
      "MARA / PALAMA",
      "RAHAMA",
      "RAUTA / GEJI",
      "RIBINA",
      "TAMA",
      "TILDEN FULANI",
      "TORO / TULAI",
      "WONU",
      "ZALAU / RISHI",
    ],
  },
  {
    state: "BAUCHI",
    lga: "WARJI",
    wards: [
      "BAIMA SOUTH/EAST",
      "BAIMA NORTH / WEST",
      "DAGU EAST",
      "DAGU WEST",
      "GABANGA",
      "KATANGA",
      "KILBORI",
      "RANGAN",
      "TIYIN",
      "TUDUN WADA WEST",
    ],
  },
  {
    state: "BAUCHI",
    lga: "ZAKI",
    wards: [
      "ALANGAWARI / KAFIN / LARABAWA",
      "BURSALI",
      "GUMAI",
      "KATAGUM",
      "MAINAKO",
      "MAIWA",
      "MAKAWA",
      "MURMUR SOUTH",
      "MURMUR NORTH",
      "SAKWA",
      "TASHENA / GADAI",
    ],
  },
  // ABUJA
  {
    state: "ABUJA-FCT",
    lga: "ABAJI",
    wards: [
      "Abaji Central",
      "Abaji North East",
      "Abaji South East",
      "Agyana/pandagi",
      "Alu Mamagi",
      "Gawu",
      "Gurdi",
      "Nuku",
      "Rimba Ebagi",
      "Yaba",
    ],
  },
  {
    state: "ABUJA-FCT",
    lga: "ABUJA MUNICIPAL",
    wards: [
      "City Centre",
      "Garki",
      "Gui",
      "Gwagwa",
      "Gwarinpa",
      "Jiwa",
      "Kabusa",
      "Karshi",
      "Karu",
      "Nyanya",
      "Orozo",
      "Wuse",
    ],
  },
  {
    state: "ABUJA-FCT",
    lga: "BWARI",
    wards: [
      "Bwari Central",
      "Byazhin",
      "Dutse Alhaji",
      "Igu",
      "Kawu",
      "Kubwa",
      "Kuduru",
      "Shere",
      "Ushafa",
      "Usuma",
    ],
  },
  {
    state: "ABUJA-FCT",
    lga: "GWAGWALADA",
    wards: [
      "Dobi",
      "Gwagwalada Centre",
      "Gwako",
      "Ibwa",
      "Ikwa",
      "Kutunku",
      "Paiko",
      "Staff Quarters",
      "Tungan Maje",
      "Zuba",
    ],
  },
  {
    state: "ABUJA-FCT",
    lga: "KWALI",
    wards: [
      "ASHARA",
      "DAFA",
      "GUMBO",
      "KILANKWA",
      "KUNDU",
      "KWALI CENTRAL",
      "PAI",
      "YANGOJI",
      "YEBU",
      "WAKO",
    ],
  },
  {
    state: "ABUJA-FCT",
    lga: "KUJE",
    wards: [
      "CHIBIRI",
      "GAUBE",
      "GUDUNKARIYA",
      "GWARGWADA",
      "KABI",
      "KUJE CENTRAL",
      "KUJEKWA",
      "KWAKU",
      "RUBOCHI",
      "YENCHE",
    ],
  },
  //   Nasarawa state
  {
    state: "NASARAWA",
    lga: "AKWANGA",
    wards: [
      "AGYAGA",
      "AKWANGA EAST",
      "AKWANGA WEST",
      "ANCHO NIGHAAN",
      "ANCHOBABA",
      "ANDAHA",
      "GUDI",
      "GWANJE .GWANJE",
      "MOROA",
      "NINGO / BOHAR",
      "NUNKU",
    ],
  },
  {
    state: "NASARAWA",
    lga: "AWE",
    wards: [
      "AKIRI",
      "AZARA",
      "GALADIMA",
      "JANGARU",
      "KANJE/ABUNI",
      "MADAKI",
      "MAKWANGIJI",
      "RIBI",
      "TUNGA",
      "WUSE",
    ],
  },
  {
    state: "NASARAWA",
    lga: "DOMA",
    wards: [
      "AGBASHI",
      "AKPANAJA",
      "ALAGYE",
      "DOKA",
      "GALADIMA",
      "MADAUCHI",
      "RUKUBI",
      "SABON GARI",
      "SARKIN DAWAKI",
      "UNGWAN MADAKI",
    ],
  },
  {
    state: "NASARAWA",
    lga: "KARU",
    wards: [
      "AGADA/BAGAJI",
      "ASO / KODAPE",
      "GITATA",
      "GURKU/KABUSU",
      "KAFIN SHANU/BETTI",
      "KARSHI I",
      "KARSHI II",
      "KARU",
      "PANDA / KARE",
      "TATTARA/KONDORO",
      "UKE",
    ],
  },
  {
    state: "NASARAWA",
    lga: "KEANA",
    wards: [
      "AGAZA",
      "ALOSHI",
      "AMIRI",
      "GIZA GALADIMA",
      "GIZA MADAKI",
      "IWAGU",
      "KADARKO",
      "KWARA",
      "OBENE",
      "OKI",
    ],
  },
  {
    state: "NASARAWA",
    lga: "KEFFI",
    wards: [
      "ANG.RIMI",
      "ANGWAN IYA I",
      "ANGWAN IYA II",
      "GANGARE TUDU",
      "JIGWADA",
      "KEFFI TOWN EAST / KOFAR GORIYA",
      "LIMAN ABAJI",
      "SABON GARI",
      "TUDUN KOFA T.V",
      "YARA",
    ],
  },
  {
    state: "NASARAWA",
    lga: "KOKONA",
    wards: [
      "AGWADA",
      "AMBA",
      "BASSA",
      "DARI",
      "GARAKU",
      "HADARI",
      "KOFAR GWARI",
      "KOKONA",
      "KOYA / KANA",
      "NINKORO",
      "YELWA",
    ],
  },
  {
    state: "NASARAWA",
    lga: "LAFIA",
    wards: [
      "ADOGI",
      "AGYARAGUN TOFA",
      "ARIKYA",
      "ASHIGIE",
      "ASSAKIO",
      "BAKIN RIJIYA/AKURBA/SARKIN PADA",
      "CHIROMA",
      "GAYAM",
      "KEFFIN/WAMBAI",
      "MAKAMA",
      "SHABU/KWANDERE",
      "WAKWA",
      "ZANWA",
    ],
  },
  {
    state: "NASARAWA",
    lga: "NASARAWA",
    wards: [
      "AKUM",
      "ARA I",
      "ARA II",
      "GUTO/AISA",
      "KANAH/ONDO/APAWU",
      "LAMINGA",
      "LOKO",
      "NASARAWA CENTRAL",
      "NASARAWA EAST",
      "NASARAWA MAIN TOWN",
      "NASARAWA NORTH",
      "ODU",
      "TUNGA/BAKONO",
      "UDENIN",
      "UDENIN GIDA",
    ],
  },
  {
    state: "NASARAWA",
    lga: "NASARAWA EGGON",
    wards: [
      "AGUNJI",
      "ALOCE/GINDA",
      "ALOGANI",
      "ENDE",
      "IGGA/BURUMBURUM",
      "IKKA WANGIBI",
      "KAGBU WANA",
      "LAMBAGA/ARIKPA",
      "LIZZIN KEFFI/EZZEN",
      "MADA STATION",
      "NASARAWA EGGON",
      "UBBE",
      "UMME",
      "WAKAMA",
    ],
  },
  {
    state: "NASARAWA",
    lga: "OBI",
    wards: [
      "ADUDU",
      "AGWATASHI",
      "DEDDERE/RIRI",
      "DUDUGURU",
      "GIDAN AUSA I",
      "GIDAN AUSA II",
      "GWADENYE",
      "KYAKALE",
      "OBI",
      "TUDUN ADABU",
    ],
  },
  {
    state: "NASARAWA",
    lga: "TOTO",
    wards: [
      "BUGAKARMO",
      "DAUSU",
      "GADAGWA",
      "GWARGWADA",
      "KANYEHU",
      "KATAKPA I",
      "SHAFAN ABAKPA I",
      "SHAFAN KWATTO I",
      "SHEGE I",
      "TOTO",
      "UGYA",
      "UMAISHA",
    ],
  },
  {
    state: "NASARAWA",
    lga: "WAMBA",
    wards: [
      "ARUM",
      "GITTA",
      "JIMIYA",
      "KONVAH",
      "KWARA",
      "MANGAR",
      "NAKERE",
      "WAMBA EAST",
      "WAMBA WEST",
      "WAYO",
    ],
  },
  {
    state: "KADUNA",
    lga: "BIRNIN GWARI",
    wards: [
      "DOGON DAWA",
      "GAYAM",
      "KAKANGI",
      "KAZAGE",
      "KUTEMESI",
      "KUYELO",
      "MAGAJIN GARI I",
      "MAGAJIN GARI II",
      "MAGAJIN GARI III",
      "RANDAGI",
      "TABANNI",
    ],
  },
  {
    state: "KADUNA",
    lga: "CHIKUN",
    wards: [
      "CHIKUN",
      "GWAGWADA",
      "KAKAU",
      "KUJAMA",
      "KUNAI",
      "KURIGA",
      "NARAYI",
      "NASARAWA",
      "RIDO",
      "S/GGARIN AREWA TIRKANIYA",
      "SABON TASHA",
      "UNG. YELWA",
    ],
  },
  {
    state: "KADUNA",
    lga: "GIWA",
    wards: [
      "DANMAHAWAYI",
      "GALADIMAWA",
      "GANGARA",
      "GIWA",
      "IDASU",
      "KADAGE",
      "KAKANGI",
      "KIDANDAN",
      "PAN HAUYA",
      "SHIKA",
      "YAKAWADA",
    ],
  },
  {
    state: "KADUNA",
    lga: "IGABI",
    wards: [
      "AFAKA",
      "BIRNIN YERO",
      "GADAN GAYAN",
      "GWARAJI",
      "IGABI",
      "KERAWA",
      "KWARAU",
      "RIGACHIKUN",
      "RIGASA",
      "SABON BIRNIN DAJI",
      "TURUNKU",
      "ZANGON AYA",
    ],
  },
  {
    state: "KADUNA",
    lga: "IKARA",
    wards: [
      "AUCHAN",
      "IKARA",
      "JANFALA",
      "K/KOGI",
      "KUYA",
      "PAKI",
      "PALA",
      "RUMI",
      "SAULAWA",
      "SAYA-SAYA",
    ],
  },
  {
    state: "KADUNA",
    lga: "JABA",
    wards: [
      "CHORI",
      "DADDU",
      "DURA/BITARO",
      "FADA",
      "FAI",
      "NDUYAH",
      "NOK",
      "SABCHEM",
      "SABZURO",
      "SAMBAM",
    ],
  },
  {
    state: "KADUNA",
    lga: "JEMA'A",
    wards: [
      "ASSO",
      "ATUKU",
      "BEDDE",
      "GIDAN WAYA",
      "GODOGODO",
      "JAGINDI",
      "KAFANCHAN 'A'",
      "KAFANCHAN 'B'",
      "KAGOMA",
      "KANINKON",
      "MAIGIZO 'A'",
      "TAKAU 'B'",
    ],
  },
  {
    state: "KADUNA",
    lga: "KACHIA",
    wards: [
      "AGUNU",
      "ANKWA",
      "AWON",
      "BISHINI",
      "DOKA",
      "GIDAN TAGWAI",
      "GUMEL",
      "KACHIA URBAN",
      "KATARI",
      "KURMIN MUSA",
      "KWATURU",
      "SABON SARKI",
    ],
  },
  {
    state: "KADUNA",
    lga: "KADUNA NORTH",
    wards: [
      "BADARAWA",
      "GABASAWA",
      "GAJI",
      "HAYIN BANKI",
      "KABALA COSTAIN/ DOKI",
      "KAWO",
      "MAIBURJI",
      "SHABA",
      "UNGUWAN DOSA",
      "UNGUWAN LIMAN",
      "UNGUWAN SARKI",
      "UNGUWAN SHANU",
    ],
  },
  {
    state: "KADUNA",
    lga: "KADUNA SOUTH",
    wards: [
      "BADIKO",
      "BARNAWA",
      "KAKURI GWARI",
      "KAKURI HAUSA",
      "MAKERA",
      "SABON GARI NORTH",
      "SABON GARI SOUTH",
      "TELEVISION",
      "TUDUN NUWAPA",
      "TUDUN WADA NORTH",
      "TUDUN WADA SOUTH",
      "TUDUN WADA WEST",
      "UNG. SANUSI",
    ],
  },
  {
    state: "KADUNA",
    lga: "KAGARKO",
    wards: [
      "ARIBI",
      "IDDAH",
      "JERE NORTH",
      "JERE SOUTH",
      "KAGARKO NORTH",
      "KAGARKO SOUTH",
      "KATUGAL",
      "KUKUI",
      "KURMIN JIBRIN",
      "KUSHE",
    ],
  },
  {
    state: "KADUNA",
    lga: "KAJURU",
    wards: [
      "AFOGO",
      "BUDA",
      "IDON",
      "KAJURU",
      "KALLAH",
      "KASUWAN MAGANI",
      "KUFANA",
      "MARO",
      "RIMAU",
      "TANTATU",
    ],
  },
  {
    state: "KADUNA",
    lga: "KAURA",
    wards: [
      "AGBAN",
      "BONDON",
      "FADA",
      "KADARKO",
      "KAURA",
      "KPAK",
      "KUKUM",
      "MALLAGUM",
      "MANCHOK",
      "ZANKAN",
    ],
  },
  {
    state: "KADUNA",
    lga: "KAURU",
    wards: [
      "BADURUM SAMA",
      "BITAL",
      "DAMAKASUWA",
      "DAWAKI",
      "GESHERE",
      "KAMARU",
      "KAURU EAST",
      "KAURU WEST",
      "KWASSAM",
      "MAKAMI",
      "PARI",
    ],
  },
  {
    state: "KADUNA",
    lga: "KUBAU",
    wards: [
      "ANCHAU",
      "DAMAU",
      "DUTSEN WAI",
      "HASKIYA",
      "KARGI",
      "KARREH",
      "KUBAU",
      "MAH",
      "PAMBEGUA",
      "ZABI",
      "ZUNTU",
    ],
  },
  {
    state: "KADUNA",
    lga: "KUDAN",
    wards: [
      "DOKA",
      "GARU",
      "HUNKUYI",
      "KAURAN WALI NORTH",
      "KAURAN WALI SOUTH",
      "KUDAN",
      "LIKORO",
      "SABON GARI HUNKUYI",
      "TABAN SANI",
      "ZABI",
    ],
  },
  {
    state: "KADUNA",
    lga: "LERE",
    wards: [
      "ABADAWA",
      "DAN ALHAJI",
      "GARU",
      "GURE/KAHUGU",
      "KAYARDA",
      "LAZURU",
      "LERE",
      "RAMIN KURA",
      "SABON BIRNIN",
      "SAMINAKA",
      "YAR KASUWA",
    ],
  },
  {
    state: "KADUNA",
    lga: "MAKARFI",
    wards: [
      "DANDAMISA",
      "DANGUZIRI",
      "GAZARA",
      "GIMI",
      "GUBUCHI",
      "GWANKI",
      "MAKARFI",
      "MAYERE",
      "NASSARWAN DOYA",
      "TUDUN WADA",
    ],
  },
  {
    state: "KADUNA",
    lga: "SABON GARI",
    wards: [
      "BASAWA",
      "BOMO",
      "CHIKAJI",
      "DOGARAWA",
      "HANWA",
      "JAMA'A",
      "JUSHIN WAJE",
      "MUCHIA",
      "SAMARU",
      "UNGUWAN GABAS",
      "ZABI",
    ],
  },
  {
    state: "KADUNA",
    lga: "SANGA",
    wards: [
      "ABORO",
      "ARAK",
      "AYU",
      "BOKANA",
      "FADAN KARSHI",
      "GWANTU",
      "NANDU",
      "NINZAM NORTH",
      "NINZAM SOUTH",
      "NINZAM WEST",
      "WASA STATION",
    ],
  },
  {
    state: "KADUNA",
    lga: "SOBA",
    wards: [
      "DAN WATA",
      "GAMAGIRA",
      "GARUN GWANKI",
      "GIMBA",
      "KINKIBA",
      "KWASSALLO",
      "MAIGANA",
      "RAHAMA",
      "RICHIFA",
      "SOBA",
      "TURAWA",
    ],
  },
  {
    state: "KADUNA",
    lga: "ZANGON KATAF",
    wards: [
      "GIDAN JATAU",
      "GORA",
      "KAMANTAN",
      "KAMURU IKULU NORTH",
      "MADAKIYA",
      "UNGUWAR GAIYA",
      "UNGUWAR RIMI",
      "ZAMAN DABO",
      "ZANGO URBAN",
      "ZONKWA",
      "ZONZON",
    ],
  },
  {
    state: "KADUNA",
    lga: "ZARIA",
    wards: [
      "DAMBO",
      "DUTSEN ABBA",
      "GYALLESU",
      "KAURA",
      "KUFENA",
      "KWARBAI A",
      "KWARBAI B",
      "LIMANCIN-KONA",
      "TUDUN WADA",
      "TUKUR TUKUR",
      "UNG. FATIKA",
      "UNG. JUMA",
      "WUCICCIRI",
    ],
  },
  {
    state: "KANO",
    lga: "AJINGI",
    wards: [
      "AJINGI",
      "BALARE",
      "CHULA",
      "DABIN KANAWA",
      "DUNDUN",
      "GAFASA",
      "GURDUBA",
      "KUNKURAWA",
      "TORANKE",
      "UNGAWAR BAI",
    ],
  },
  {
    state: "KANO",
    lga: "ALBASU",
    wards: [
      "ALBASU CENTRAL",
      "BATAIYA",
      "CHAMARANA",
      "DAHO",
      "FANDA",
      "FARAGAI",
      "GAGARAME",
      "HUNGU",
      "SAYA-SAYA",
      "TSANGAYA",
    ],
  },
  {
    state: "KANO",
    lga: "BAGWAI",
    wards: [
      "BAGWAI",
      "DANGADA",
      "GADANYA",
      "GOGORI",
      "KIYAWA",
      "KWAJALI",
      "RIMIN DAKO",
      "ROMO",
      "SARE-SARE",
      "WURO BAGGA",
    ],
  },
  {
    state: "KANO",
    lga: "BEBEJI",
    wards: [
      "ANADARIYA",
      "BAGUDA",
      "BEBEJI",
      "DAMAU",
      "DURMAWA",
      "GARGAI",
      "GWARMAI",
      "KOFA",
      "KUKI",
      "RAHAMA",
      "RANKA",
      "RANTAN",
      "TARIWA",
      "WAK",
    ],
  },
  {
    state: "KANO",
    lga: "BICHI",
    wards: [
      "BADUME",
      "BICHI",
      "DANZABUWA",
      "FAGOLO",
      "KAUKAU",
      "KWAMARAWA",
      "KYALLI",
      "MUNTSIRA",
      "SAYE",
      "WAIRE",
      "YALLAMI",
    ],
  },
  {
    state: "KANO",
    lga: "BUNKURE",
    wards: [
      "BARKUM",
      "BONO",
      "BUNKURE",
      "CHIRIN",
      "GAFAN",
      "GURJIYA",
      "GWAMMA",
      "KULLUWA",
      "KUMURYA",
      "SANDA",
    ],
  },
  {
    state: "KANO",
    lga: "DALA",
    wards: [
      "ADAKAWA",
      "BAKIN RUWA",
      "DALA",
      "DOGON NAMA",
      "GOBIRAWA",
      "GWAMMAJA",
      "KABUWAYA",
      "KANTUDU",
      "KOFAR MAZUGAL",
      "KOFAR RUWA",
      "MADIGAWA",
      "YALWA",
    ],
  },
  {
    state: "KANO",
    lga: "DANBATTA",
    wards: [
      "AJUMAWA",
      "DANBATTA EAST",
      "DANBATTA WEST",
      "FAGWALAWA",
      "GORON MAJE",
      "GWANDA",
      "GWARABJAWA",
      "KORE",
      "SAIDAWA",
      "SANSAN",
    ],
  },
  {
    state: "KANO",
    lga: "DAWAKI KUDU",
    wards: [
      "DABAR KWARI",
      "DANBAGIWA",
      "DAWAKI",
      "DAWAKIJI",
      "DOSAN",
      "GANO",
      "GURJIYA",
      "JIDO",
      "TAMBURAWA",
      "TSAKUWA",
      "UNGUWAR DUNIYA",
      "YANBARAU",
      "YANKATSARI",
      "YARGAYA",
      "ZOGARAWA",
    ],
  },
  {
    state: "KANO",
    lga: "DAWAKI TOFA",
    wards: [
      "DAN GUGUWA",
      "DAWAKI EAST",
      "DAWAKI WEST",
      "DAWANAU",
      "GANDUJE",
      "GARGARI",
      "JALLI",
      "KWA",
      "MARKE",
      "TATTARAWA",
      "TUMFAFI",
    ],
  },
  {
    state: "KANO",
    lga: "DOGUWA",
    wards: [
      "DARIYA",
      "DOGON KAWO",
      "DUGUWA",
      "FALGORE",
      "MARAKU",
      "RAGADA",
      "RIRIWAI",
      "TAGWAYE",
      "UNGUWAR NATSOHUWA",
      "ZAINABI",
    ],
  },
  {
    state: "KANO",
    lga: "FAGGE",
    wards: [
      "FAGGE A",
      "FAGGE B",
      "FAGGE C",
      "FAGGE D",
      "FAGGE E",
      "KWACHIRI",
      "RIJIYAR LEMO",
      "SABONGARI EAST",
      "SABONGARI WEST",
      "YAMMATA",
    ],
  },
  {
    state: "KANO",
    lga: "GABASAWA",
    wards: [
      "GABASAWA",
      "GARUN DANGA",
      "JODA",
      "KARMAKI",
      "MEKIYA",
      "TARAUNI",
      "YANTAR AREWWA",
      "YAUTAR KUDU",
      "YUMBU",
      "ZAKIRAI",
      "ZUGACHI",
    ],
  },
  {
    state: "KANO",
    lga: "GARKO",
    wards: [
      "DAL",
      "GARIN ALI",
      "GARKO",
      "GURJIYA",
      "KAFIN MALAMAI",
      "KATUMARI",
      "KWAS",
      "RABA",
      "SARINA",
      "ZAKARAWA",
    ],
  },
  {
    state: "KANO",
    lga: "GARUN MALAM",
    wards: [
      "CHIROMAWA",
      "DORAWAR-SALLAU",
      "FANKURUN",
      "GARUN BABBA",
      "GARUN MALAM",
      "JOBAWA",
      "KADAWA",
      "MAKWARO",
      "YAD AKWARI",
      "YALWAN YADAKWARI",
    ],
  },
  {
    state: "KANO",
    lga: "GAYA",
    wards: [
      "BALAN",
      "GAMARYA",
      "GAMOJI",
      "GAYA AREWA",
      "GAYA KUDU",
      "KADEMI",
      "KAZURAWA",
      "MAIMAKAWA",
      "SHAGOGO",
      "WUDILAWA",
    ],
  },
  {
    state: "KANO",
    lga: "GEZAWA",
    wards: [
      "BABAWA",
      "GAWO",
      "GEZAWA",
      "JOGANA",
      "KETAWA",
      "MESAR-TUDU",
      "SARARIN-GEZAWA",
      "TSAMIYA-BABBA",
      "TUMBAU",
      "WANGARA",
      "ZANGO",
    ],
  },
  {
    state: "KANO",
    lga: "GWALE",
    wards: [
      "DANDAGO",
      "DISO",
      "DORAYI",
      "GALADANCHI",
      "GORON DUTSE",
      "GWALE",
      "GYARANYA",
      "KABUGA",
      "MANDAWARI",
      "SANI MAI MAGGE",
    ],
  },
  {
    state: "KANO",
    lga: "GWARZO",
    wards: [
      "GETSO",
      "GWARZO",
      "JAMA' A",
      "KARA",
      "KUTAMA",
      "LAKWAYA",
      "MADADI",
      "MAINIKA",
      "SABON BIRNI",
      "UNGUWAR TUDU",
    ],
  },
  {
    state: "KANO",
    lga: "KABO",
    wards: [
      "DUGABAU",
      "DURUN",
      "GAMMO",
      "GARO",
      "GODIYA",
      "GUDE",
      "HAUWADE",
      "KABO",
      "KANWA",
      "MASANAWA",
    ],
  },
  {
    state: "KANO",
    lga: "KANO MUNICIPAL",
    wards: [
      "CHEDI",
      "DAN'AGUNDI",
      "GANDUN ALBASA",
      "JAKARA",
      "KANKAROFI",
      "SHAHUCHI",
      "SHARADA",
      "SHESHE",
      "TUDUN NUFAWA",
      "TUDUN WAZIRCHI",
      "YAKASAI",
      "ZAITAWA",
      "ZANGO",
    ],
  },
  {
    state: "KANO",
    lga: "KARAYE",
    wards: [
      "DAURA",
      "KAFIN DAFGA",
      "KARAYE",
      "KURUGU",
      "KWANYAWA",
      "TUDUN KAYA",
      "TURAWA",
      "UNGUWAR HAJJI",
      "YAMMEDI",
      "YOLA",
    ],
  },
  {
    state: "KANO",
    lga: "KIBIYA",
    wards: [
      "DURBA",
      "FAMMAR",
      "FASSI",
      "KADIGAWA",
      "KAHU",
      "KIBIYA I",
      "KIBIYA II",
      "NARIYA",
      "TARAI",
      "UNGUWAR GAI",
    ],
  },
  {
    state: "KANO",
    lga: "KUMBOTSO",
    wards: [
      "CHALLAWA",
      "CHIRANCHI",
      "DANBARE",
      "DANMALIKI",
      "GURINGAWA",
      "KUMBOTSO",
      "KUREKEN SANI",
      "MARIRI",
      "NA'IBAWA",
      "PANSHEKARA",
      "UNGUWAR RIMI",
    ],
  },
  {
    state: "KANO",
    lga: "KUNCHI",
    wards: [
      "BUMAI",
      "GARIN SHEME",
      "GWARMAI",
      "KASUWAR KUKA",
      "KUNCHI",
      "MATAN FADA",
      "RIDAWA",
      "SHAMAKAWA",
      "SHUWAKI",
      "YANDADI",
    ],
  },
  {
    state: "KANO",
    lga: "KURA",
    wards: [
      "DALILI",
      "DAN HASSAN",
      "DUKAWA",
      "GUNDUTSE",
      "KARFI",
      "KOSAWA",
      "KURA",
      "KURUNSUMAU",
      "RIGAR DUKA",
      "TANAWA",
    ],
  },
  {
    state: "KANO",
    lga: "MADOBI",
    wards: [
      "BURJI",
      "CINKOSO",
      "GALINJA",
      "GORA",
      "KAFIN AGUR",
      "KANWA",
      "KAURA MATA",
      "KUBARACI",
      "KWANKWASO",
      "MADOBI",
      "RIKADAWA",
    ],
  },
  {
    state: "KANO",
    lga: "MAKODA",
    wards: [
      "BABBAR RIGA",
      "DURMA",
      "JIBGA",
      "KADANDANI",
      "KOGUNA",
      "KOREN TATSO",
      "MAITSIDAU",
      "MAKODA",
      "SATAME",
      "TANGAJI",
      "WAILARE",
    ],
  },
  {
    state: "KANO",
    lga: "MINJIBIR",
    wards: [
      "AZORE",
      "GANDURWAWA",
      "KANTAMA",
      "KUNYA",
      "KURU",
      "KWARKIYA",
      "MINJIBIR",
      "SARBI",
      "TSAKIYA",
      "TSAKUWA",
      "WASAI",
    ],
  },
  {
    state: "KANO",
    lga: "NASARAWA-KANO",
    wards: [
      "DAKATA",
      "GAMA",
      "GAWUNA",
      "GIGINYU",
      "GWAGWARWA",
      "HOTORO NORTH",
      "HOTORO SOUTH",
      "KAURA GOJE",
      "KAWAJI",
      "TUDUN MURTALA",
      "TUDUN WADA",
    ],
  },
  {
    state: "KANO",
    lga: "RANO",
    wards: [
      "DAWAKI",
      "LAUSU",
      "MADACHI",
      "RANO",
      "RURUM SABON-GARI",
      "RURUM TSOHON-GARI",
      "SAJI",
      "YALWA",
      "ZINYAU",
      "ZURGU",
    ],
  },
  {
    state: "KANO",
    lga: "RIMIN GADO",
    wards: [
      "BUTU-BUTU",
      "DAWAKI GULU",
      "DOKA DAWA",
      "DUGURAWA",
      "GULU",
      "JILI",
      "KAROFIN YASHI",
      "RIMIN GADO",
      "SAKARATSA",
      "TAMAWA",
      "YALWAN DANZIYAL",
      "ZANGO DAN ABDU",
    ],
  },
  {
    state: "KANO",
    lga: "ROGO",
    wards: [
      "BELI",
      "FALGORE",
      "FULATAN",
      "GWANGWAN",
      "JAJAYE",
      "ROGO RUMA",
      "ROGO SABON GARI",
      "RUWAN BAGO",
      "ZAREWA",
      "ZOZA",
    ],
  },
  {
    state: "KANO",
    lga: "SHANONO",
    wards: [
      "ALAJAWA",
      "DUTSEN-BAKOSHI",
      "FARURUWA",
      "GORON DUTSE",
      "KADAMU",
      "KOKIYA",
      "LENI",
      "SHAKOGI",
      "SHANONO",
      "TSAURE",
    ],
  },
  {
    state: "KANO",
    lga: "SUMAILA",
    wards: [
      "GALA",
      "GANI",
      "GARFA",
      "GEDIYA",
      "KANAWA",
      "MAGAMI",
      "MASU",
      "RIMI",
      "RUMO",
      "SITTI",
      "SUMAILA",
    ],
  },
  {
    state: "KANO",
    lga: "TAKAI",
    wards: [
      "BAGWARO",
      "DURBUNDE",
      "FAJEWA",
      "FALALI",
      "FARURUWA",
      "KACHAKO",
      "KARFI",
      "KUKA",
      "TAKAI",
      "ZUGA",
    ],
  },
  {
    state: "KANO",
    lga: "TARAUNI",
    wards: [
      "BABBAN GIJI",
      "DARMANAWA",
      "DAURAWA",
      "GYADI-GYADI AREWA",
      "GYADI-GYADI KUDU",
      "HOTORO (NNPC)",
      "KAUYEN ALU",
      "TARAUNI",
      "UNGUWA UKU",
      "UNGUWAR GANO",
    ],
  },
  {
    state: "KANO",
    lga: "TOFA",
    wards: [
      "DINDERE",
      "DOKA",
      "GAJIDA",
      "GINSAWA",
      "JANGUZA",
      "JAUBEN KUDU",
      "KWAMI",
      "LAMBU",
      "LANGEL",
      "TOFA",
      "UNGUWAR RIMI",
      "WANGARA",
      "YALWA KARAMA",
      "YANOKO",
      "YARIMAWA",
    ],
  },
  {
    state: "KANO",
    lga: "TSANYAWA",
    wards: [
      "DADDARAWA",
      "DUNBULUN",
      "GOZAKI",
      "GURUN",
      "KABAGIWA",
      "TATSAN",
      "TSANYAWA",
      "YANGANAU",
      "YANKAMAYE",
      "ZAROGI",
    ],
  },
  {
    state: "KANO",
    lga: "TUDUN WADA",
    wards: [
      "BABURI",
      "BURUMBURUM",
      "DALAWA",
      "JANDUTSE",
      "JITA",
      "KAREFA",
      "NATA'ALA",
      "SABON GARI",
      "SHUWAKI",
      "TSOHOGARI",
    ],
  },
  {
    state: "KANO",
    lga: "UNGOGO",
    wards: [
      "BACHIRAWA",
      "GAYAWA",
      "KADAWA",
      "KARO",
      "PANISAU",
      "RANGAZA",
      "RIJIYAR ZAKI",
      "TUDUN FULANI",
      "UNGOGO",
      "YADAKUNYA",
      "ZANGO",
    ],
  },
  {
    state: "KANO",
    lga: "WARAWA",
    wards: [
      "AMARAWA",
      "DANLASAN",
      "GARIN DAU",
      "GOGEL",
      "IMAWA",
      "J/GALADIMA",
      "JEMAGU",
      "JIGAWA",
      "KATARKAWA",
      "MADARI MATA",
      "TAMBURAWAR GABAS",
      "TANGAR",
      "WARAWA",
      "'YAN DALLA",
      "'YANGIZO",
    ],
  },
  {
    state: "KANO",
    lga: "WUDIL",
    wards: [
      "ACHIKA",
      "DAGUMAWA",
      "DANKAZA",
      "DARKI",
      "INDABO",
      "KAUSANI",
      "LAJAWA",
      "SABON GARI",
      "UTAI",
      "WUDIL",
    ],
  },
];
