/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:89ed6486-5b61-4af9-94cc-035b369c166a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rfKLYbK3Q",
    "aws_user_pools_web_client_id": "5a7dl8dahgn9qs64fq595tnvth",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "triluxy-app-storage-70e7e164185456-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
